name: Bloggy app

# Trigger the workflow only on push to the main branch
on:
  pull_request:
    branches: ["main"]

jobs:
  # Linting job to ensure code style and syntax
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js version 22.x
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Install dependencies using npm ci
      - run: npm ci

      # Run the linter
      - run: npm run lint

  # # Test job runs the test suite on multiple Node.js versions
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # Matrix to test on Node.js versions 18.x, 20.x, and 22.x
  #       node-version: [18.x, 20.x, 22.x]

  #   steps:
  #     # Checkout the code
  #     - uses: actions/checkout@v4

  #     # Set up the Node.js version based on the matrix
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     # Install dependencies
  #     - run: npm ci

  #     # Run tests (ensure `npm test` is defined in your package.json)
  #     - run: npm test

  # Build job to compile or bundle the application
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js version 22.x
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Install dependencies
      - run: npm ci

      # Run build command (ensure `npm run build` is defined)
      - run: npm run build
